### ISSUE TITLE
Gebruik een externe stylesheet

### ISSUE THREAD

**Issue by rutgerkock** [OFRqq/The-client-website-2#5]
Het idee van de opdracht is dat je basis styling gebruikt uit een extern, gezamelijk bestand, via een <link> in je head, doe dit.
https://github.com/OFRqq/The-client-website-2/blob/132246dfeb816907656ba52b8ea92b13e185d90f/index.html#L4

**Comment by OFRqq** [comment]
er is een tweede link toegevoegd, de gezamelijke stylesheet, begrijp de opdracht alleen toepassen kwam helaas wat laat door onduidelijkheden, hij staat er in werkende.
