### ISSUE TITLE
De div heeft geen functie.

### ISSUE THREAD

**Issue by rutgerkock** [OFRqq/The-client-website-2#9]
Als iets geen functie heeft kan je het beter weghalen.

https://github.com/OFRqq/The-client-website-2/blob/132246dfeb816907656ba52b8ea92b13e185d90f/index.html#L56-L60

**Comment by OFRqq** [comment]
de footer is nog niet af en zal ik er uiteindelijk hoogstwaarschijnlijk div's voor nodig hebben, daarom laat ik ze er voor nu even in.
